"""Assembly block — appended to generate_tutorial.py via exec at runtime."""

# =============================================================================
# ASSEMBLE HTML
# =============================================================================
import sys as _sys
_sys.path.insert(0, str(ROOT / "docs"))
from _tut_sections import build_sections

B = dict(
    PIPELINE=B_PIPELINE, RUSSELL=B_RUSSELL, RAWEEG=B_RAWEEG,
    MARKERS=B_MARKERS, PSD=B_PSD, PREPROC_TD=B_PREPROC_TD,
    KNN=B_KNN, EPOCHS=B_EPOCHS, ROI=B_ROI, FEAT=B_FEAT,
    LOSO=B_LOSO if "B_LOSO" in dir() else "",
    CM=B_CM   if "B_CM"   in dir() else "",
    FLAGS=B_FLAGS if "B_FLAGS" in dir() else "",
)

sections_html = build_sections(
    B=B, CFG=CFG, subjects=subjects, preprocessed=preprocessed,
    roi_maps=roi_maps, feat_ds=feat_ds, loso=loso,
    summary_df=summary_df, per_subj_df=per_subj_df, flags=flags, NT=NT,
    fig_html=fig_html, callout=callout, code=code, term=term,
    schema_table=schema_table, df_table=df_table,
    section_wrap=section_wrap, subsec=subsec,
    have_now=have_now, checklist=checklist,
    mono=mono, shape_badge=shape_badge,
)

TOC_GROUPS = [
    ("Introduction", [
        ("mental",    "Mental Model (TL;DR)"),
        ("datamodel", "Data Model & Schemas"),
    ]),
    ("Pipeline Steps", [
        ("step1", "1 — Load"),
        ("step2", "2 — Preprocess"),
        ("step3", "3 — Epoch"),
        ("step4", "4 — ROI Window"),
        ("step5", "5 — MiniRocket"),
        ("step6", "6 — LOSO SVM"),
        ("step7", "7 — Stats & Flags"),
    ]),
    ("Reference", [
        ("outputs",  "Outputs"),
        ("config",   "Configuration"),
        ("recipes",  "Run Recipes"),
        ("appendix", "Paper Mapping"),
    ]),
]

sidebar_html = "".join(
    f'<h4>{grp}</h4>' + "".join(
        f'<a href="#{anchor}" class="toc-link">{label}</a>'
        for anchor, label in links
    )
    for grp, links in TOC_GROUPS
)

page = (
    "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>NeuroSense EEG Pipeline &#8212; Complete Tutorial</title>\n"
    "  <style>" + CSS + "</style>\n</head>\n<body>\n"
    "<header>\n"
    "  <h1>NeuroSense EEG Pipeline</h1>\n"
    "  <p class=\"tagline\">Complete step-by-step tutorial &mdash; "
    "from raw XDF file to emotion classification results</p>\n"
    "  <div class=\"badges\">\n"
    "    <span class=\"badge g\">15/15 tests passing</span>\n"
    "    <span class=\"badge b\">Python 3.12</span>\n"
    "    <span class=\"badge\">MiniRocket + SVM</span>\n"
    "    <span class=\"badge\">LOSO cross-validation</span>\n"
    "    <span class=\"badge\">IEEE Access paper</span>\n"
    "    <span class=\"badge\">4-channel Muse EEG</span>\n"
    "  </div>\n</header>\n\n"
    "<div class=\"layout\">\n"
    "  <aside>\n" + sidebar_html + "\n  </aside>\n"
    "  <main>\n" + "\n".join(sections_html) + "\n  </main>\n"
    "</div>\n\n"
    "<footer>\n"
    "  Generated by <code>docs/generate_tutorial.py</code> &mdash;\n"
    "  NeuroSense EEG Pipeline &mdash;\n"
    "  <a href=\"https://github.com/a1441/NeuroSense-Modules\">"
    "github.com/a1441/NeuroSense-Modules</a>\n</footer>\n\n"
    "<script>\n"
    "const links = document.querySelectorAll('a.toc-link');\n"
    "const observer = new IntersectionObserver(entries => {\n"
    "  entries.forEach(e => {\n"
    "    if (e.isIntersecting) {\n"
    "      links.forEach(l => l.classList.remove('active'));\n"
    "      const a = document.querySelector('a[href=\"#' + e.target.id + '\"]');\n"
    "      if (a) a.classList.add('active');\n"
    "    }\n"
    "  });\n"
    "}, {threshold: 0.2});\n"
    "document.querySelectorAll('section[id]').forEach(s => observer.observe(s));\n"
    "</script>\n</body>\n</html>"
)

out = ROOT / "docs" / "tutorial.html"
out.write_text(page, encoding="utf-8")
print(f"Tutorial written -> {out.resolve()}")
print(f"Size: {out.stat().st_size // 1024} KB")
